name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install hugo-book theme
        run: git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book; cp -R themes/hugo-book/exampleSite/content.en/* ./content

      - name: Build
        run: hugo --minify --theme hugo-book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public